/** lib/aurora/examples.ts — example programs shipped with the playground. */
// Sources copied verbatim from aurora-vm/examples/*.asm

export interface AuroraExample { id: string; name: string; source: string; }

export const EXAMPLES: AuroraExample[] = [
  { id: "hello", name: "hello.asm", source: "; examples/hello.asm -- Hello, world! via OUTC loop over a DB string.\n;\n; Assembled with: python3 tools/aurora-asm examples/hello.asm -o hello.bin\n; Run with:       ./build/aurora run hello.bin\n\n    MOV R0, msg        ; R0 = address of the string\nloop:\n    LOADB R1, [R0]     ; next byte\n    CMP R1, 0\n    JE done            ; null terminator ends the loop\n    OUTC R1            ; print one character\n    ADD R0, 1\n    JMP loop\ndone:\n    MOV R0, 0        ; clean exit code\n    HALT\n\nmsg: DB \"Hello, world!\", 10, 0\n" },
  { id: "fib", name: "fib.asm", source: "; examples/fib.asm -- fib(10) = 55, iterative.\n\n    MOV R0, 0         ; a = fib(0)\n    MOV R1, 1         ; b = fib(1)\n    MOV R2, 10        ; iterations remaining\nloop:\n    MOV R3, R0\n    ADD R3, R1        ; R3 = a + b\n    MOV R0, R1        ; a = b\n    MOV R1, R3        ; b = a + b\n    DEC R2\n    CMP R2, 0\n    JG loop\n    OUT R0            ; prints \"55\"\n    HALT\n" },
  { id: "factorial", name: "factorial.asm", source: "; examples/factorial.asm -- 10! = 3628800.\n\n    MOV R0, 1         ; result\n    MOV R1, 10        ; counter\nloop:\n    MUL R0, R1\n    DEC R1\n    CMP R1, 1\n    JG loop\n    OUT R0            ; prints \"3628800\"\n    HALT              ; exit code = 3628800 & 0xFF = 0\n" },
  { id: "arithmetic", name: "arithmetic.asm", source: "; examples/arithmetic.asm -- (20 + 10) * 3 = 90.\n; The exact bytes are worked out in docs/ISA.md section 11.\n\n    MOV R0, 20\n    MOV R1, 10\n    ADD R0, R1        ; R0 = 30\n    MOV R2, 3\n    MUL R0, R2        ; R0 = 90\n    OUT R0            ; prints \"90\"\n    HALT              ; exit code = 90\n" },
  { id: "loop", name: "loop.asm", source: "; examples/loop.asm -- count 1..5 with a conditional loop.\n\n    MOV R0, 1\nloop:\n    OUT R0            ; print 1, 2, 3, 4, 5\n    INC R0\n    CMP R0, 6\n    JL loop\n    HALT\n" },
  { id: "memory", name: "memory.asm", source: "; examples/memory.asm -- 64-bit and byte memory round-trips.\n\n    MOV R0, 0x1000\n    MOV R1, 0x5A5A\n    STORE [R0], R1    ; mem64[0x1000] = 0x5A5A\n    MOV R2, 0\n    LOAD R2, [0x1000] ; R2 = 0x5A5A\n    CMP R2, R1\n    JNE fail\n    OUT R2            ; prints \"23130\"\n    MOV R3, cell\n    MOV R4, 0xAB\n    STOREB [R3], R4   ; mem8[cell] = 0xAB\n    LOADB R5, [R3]    ; R5 = 0xAB\n    CMP R5, R4\n    JNE fail\n    MOV R0, 1\n    OUT R0            ; prints \"1\" (ok marker)\n    HALT\nfail:\n    MOV R0, 0\n    OUT R0\n    HALT\n\ncell: DB 0\n" },
  { id: "stack", name: "stack.asm", source: "; examples/stack.asm -- PUSH/POP LIFO order and CALL/RET.\n\n    MOV R0, 1\n    PUSH R0\n    MOV R0, 2\n    PUSH R0\n    MOV R0, 3\n    PUSH R0\n    POP R0\n    OUT R0            ; 3\n    POP R0\n    OUT R0            ; 2\n    POP R0\n    OUT R0            ; 1\n    CALL get6\n    OUT R0            ; 6\n    HALT\n\nget6:\n    MOV R0, 6\n    RET\n" },
];
